Repository nofusscomputing/ansible_collection_centurion, pull requests merged in 2024-08, with the labels that each got.

#16 ci: migrate from gitlab
  .github/workflows/ci.yaml
  .github/workflows/pull-requests.yaml
  .github/workflows/triage.yaml
  .gitlab-ci.yml
Labels: type::ci / cd

#18 ci(github): migrate CI from Gitlab to github
  .github/workflows/bump.yaml
  .github/workflows/ci.yaml
  .vscode/extensions.json
  README.md
  docs/projects/ansible/collection/centurion/index.md
  meta/runtime.yml
Labels: type::ci / cd

#28 chore: add makefile
  .github/workflows/ci.yaml
  .gitignore
  .vscode/extensions.json
  CONTRIBUTING.md
  makefile
Labels: type::quality assurance

#17 feat(playbooks): migration of centurion playbooks to github
  .ansible-lint-ignore
  docs/projects/ansible/collection/centurion/playbooks/index.md
  docs/projects/ansible/collection/centurion/playbooks/inventory.md
  docs/projects/ansible/collection/centurion/playbooks/teams.md
  docs/projects/ansible/playbooks/awx.md
  mkdocs.yml
  playbooks/inventory.yaml
  playbooks/teams.yaml
Labels: type::feature
